### ISSUE TITLE
Combination of hclust, dist with Momocs

### ISSUE THREAD

**Issue by lrocax** [vbonhomme/Momocs#107]
Following  CLUST(bp) error #102 can you provide a working example of how to use combination of hclust, dist.

Thanks

**Comment by vbonhomme** [comment]
```
 bp <- bot %>% efourier %>% PCA()
bp$x[, 1:3] %>% dist() %>% hclust() %>% plot()
```


2015-11-24 10:52 GMT+01:00 Lluis Roca <notifications@github.com>:

> Following CLUST(bp) error #102
> <https://github.com/vbonhomme/Momocs/issues/102> can you provide a
> working example of how to use combination of hclust, dist.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/107>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
