### ISSUE TITLE
Import previous landmarks?

### ISSUE THREAD

**Issue by bberger14** [vbonhomme/Momocs#122]
Is there a way to bring in landmark coordinates from other programs (e.g. tpsDIG2, Geomorph, etc.) if the placement is difficult to assess from outlines (i.e. venation is used to place landmarks on petal lobes).

**Comment by vbonhomme** [comment]
you can define them using ImageJ (or other) then use tie_jpg_txt
there is also an import_tps and and import_StereoMorph.
overall, I'm working on these import functions



2016-01-28 23:49 GMT+01:00 bberger14 <notifications@github.com>:

> Is there a way to bring in landmark coordinates from other programs (eg
> tpsDIG2, Geomorph, etc) if the placement is difficult to assess from
> outlines (ie venation is used to place landmarks on petal lobes)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/122>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by bberger14** [comment]
Thanks Vincent!

Brent

On Thu, Jan 28, 2016 at 11:45 PM, Vincent Bonhomme <notifications@github.com
> wrote:

> you can define them using ImageJ (or other) then use tie_jpg_txt
> there is also an import_tps and and import_StereoMorph.
> overall, I'm working on these import functions
>
>
>
> 2016-01-28 23:49 GMT+01:00 bberger14 <notifications@github.com>:
>
> > Is there a way to bring in landmark coordinates from other programs (eg
> > tpsDIG2, Geomorph, etc) if the placement is difficult to assess from
> > outlines (ie venation is used to place landmarks on petal lobes)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/Momocs/issues/122>.
> >
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/122#issuecomment-176584337>.
>



-- 
Brent A. Berger, Ph.D.
Postdoctoral Research Associate
Department of Biology
St. John's University
8000 Utopia Parkway
Queens, NY 11439
718-990-6790
