### ISSUE TITLE
pos.shp in an LDA plot

### ISSUE THREAD

**Issue by lrocax** [vbonhomme/Momocs#182]
I use Momocs 1.2.1 and I can not plot an LDA with pos.shp="circle" (it works with the PCA)?  Is there a way how to solve it?

Script:
if (!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github('vbonhomme/Momocs')

library(Momocs)
 
data(apodemus)
test.f <- efourier(apodemus, nb.h=32)

###PCA: Principal Component Analysis
test.p <- PCA(test.f)
plot(test.p, 1, pos.shp="circle",  chull.filled=TRUE, title="All data PCA")

###Linear Discriminant Analysis
test.l <- LDA(test.p,1)
plot(test.l, pos.shp="circle", chull.filled=TRUE,  title="All data LDA")

**Comment by vbonhomme** [comment]
Hi,
I add some problems with this function and this has long been a deprecated feature that definitely need to come back. I'm rewriting all graphics functions these days and the way everything is handled behind the curtain. Right now, you can try to survive to `LDA2shp_efourier()` but  if you can wait a bit more, in 2/3 months we will have something much more convenient. Many changes are being prepared for Momocs and its environment. Sorry for the delay by the way.
