### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by lrocax** [vbonhomme/Momocs#62]
Hi,

I am trying to learn EFA and your package look as an excellent starting point (I am working with 0.2-6).

I run the botF <- eFourier(bot, nb.h=32) in order to get the harmonic coefficients and I am looking on the botF output and I am a bit lost.
The output is:
A matrix of harmonic coefficients obtained with elliptical Fourier analysis (see ?Coe) 
******************************

General
--------------------
 - 40 outlines
 - 32 harmonics
 - 1 grouping factor defined

Some harmonic coefficients: @coe
--------------------
                  A1        A2     A3        B1        B2        B3
beer_brahma        1  0.000323 0.0928 -2.53e-16 -3.10e-03 -2.37e-04
beer_caney         1 -0.002450 0.0939 -1.43e-16  3.35e-03  7.82e-05
beer_chymay        1  0.006730 0.0716 -5.90e-17 -4.15e-03  2.69e-03
whisky_tamdhu      1 -0.000526 0.0898 -3.90e-16 -5.76e-06 -3.69e-04
whisky_wildturkey  1  0.003390 0.0893  1.07e-16  3.03e-03  3.12e-03
whisky_yoichi      1 -0.003660 0.0724 -2.48e-16 -2.93e-03  1.42e-03
                         C1        C2        C3    D1      D2     D3
beer_brahma        8.15e-17 -0.000720 -0.004100 0.292 -0.0470 0.0520
beer_caney        -1.11e-16  0.000593 -0.000658 0.300 -0.0713 0.0508
beer_chymay        1.00e-16 -0.000835 -0.003970 0.410 -0.0948 0.0469
whisky_tamdhu      5.41e-16  0.000837  0.000312 0.293 -0.0622 0.0403
whisky_wildturkey  2.85e-16 -0.001640 -0.001410 0.316 -0.0903 0.0367
whisky_yoichi     -7.83e-17  0.002850 -0.001840 0.372 -0.0707 0.0414
...

Names: @names
--------------------
beer_brahmabeer_caneybeer_chymaybeer_coronabeer_deusventrue
 ...
whisky_obanwhisky_oldpotrerowhisky_redbreast
whisky_tamdhuwhisky_wildturkeywhisky_yoichi

Factors: @fac
--------------------
type : beer whisky 

I do not understand the output, do I need to get A1…A32, B1…B32, C1…C32 and D1…D32 and this output is only summarized? Can you please explain me more what do they mean? Why in the histogram only see up to A/B/C/D4. As the natural step is to do a PCA, how does the table prior to the PCA looks like? Do I only check the A/B/C/D32?

Thanks a lot.

**Comment by vbonhomme** [comment]
Hi lluis'
Sorry very poor connection
First of all you should use 0.99 there www.vincentbonhomme.fr/momocs 
Ill be available in ten ish days
All the best
Vincent

**Comment by lrocax** [comment]
Hi,

I move to 0.99, it works but I am still puzzled by the output of bot.p.

I will wait for your reply.

Thanks

**Comment by vbonhomme** [comment]
these are amplitude of harmonic coefficients
ranked this way : A1, A2, ... An, B1, ..., Bn, C1, ..., Cn, D1, ..., Dn
you can access them directly( as a matrix) with bot.p$coe

hope this helps,
v


2015-02-07 9:19 GMT+01:00 Lluis Roca <notifications@github.com>:

> Hi,
>
> I move to 0.99, it works but I am still puzzled by the output of bot.p.
>
> I will wait for your reply.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/62#issuecomment-73355262>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by lrocax** [comment]
Dear Vincent,

Thanks a lot for the reply. It helps a lot.

Did you mean to check the bot.f$coe? bot.p$coe is NULL
 
Does the PCA is performed on all the bot.f$coe matrix?

The script I used:
library(Momocs)
data(bot)
bot
panel(bot, names=TRUE, fac="type")
bot.f <- efourier(bot, nb.h=12)
bot.f$coe
bot.p <- PCA(bot.f)
bot.p$coe
plot(bot.p, "type")

Thanks again.

**Comment by vbonhomme** [comment]
Dear Lluis,

bot.p$coe must be NULL since it's not defined. bot.p is a PCA (-class)
object on which you can retrieve scores (bot.p$x) and other things like
plot(bot.p) and many options (?plot.PCA) and also the next PCA plotter with
plot2(bot.p)

On the example provided, PCA will use the matrix of coefficients (without
rescaling). Have a look to ?PCA for more options.

hth

v

2015-02-07 18:19 GMT+01:00 Lluis Roca <notifications@github.com>:

> Dear Vincent,
>
> Thanks a lot for the reply. It helps a lot.
>
> Did you mean to check the bot.f$coe? bot.p$coe is NULL
>
> Does the PCA is performed on all the bot.f$coe matrix?
>
> The script I used:
> library(Momocs)
> data(bot)
> bot
> panel(bot, names=TRUE, fac="type")
> bot.f <- efourier(bot, nb.h=12)
> bot.f$coe
> bot.p <- PCA(bot.f)
> bot.p$coe
> plot(bot.p, "type")
>
> Thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/62#issuecomment-73373212>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by lrocax** [comment]
Thanks.

Just to be sure, do you perform the PCA on all the data.frame (bot.f$coe)?

Why do you run the LDA(PCA(bot.f) like that? cant you run it directly without the PCA?

Thanks.

**Comment by lrocax** [comment]
Hi,

Can you please reply my last issues above.

Thanks.

**Comment by vbonhomme** [comment]
* PCA are calculated on the slot $coe (of any xxxCoe object). The PCA can
be done with options (thos of prcomp, see ?PCA)
* We run the LDA on PC scores because we reduce collinearity between some
coefficients (particularly H1). You still can do it with lda (from package
MASS) lda(yourCoeObject$coe, etc.)


2015-02-09 21:28 GMT+01:00 Lluis Roca <notifications@github.com>:

> Thanks.
>
> Just to be sure, do you perform the PCA on all the data.frame (bot.f$coe)?
>
> Why do you run the LDA(PCA(bot.f) like that? cant you run it directly
> without the PCA?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/62#issuecomment-73583604>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
