### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by JohnJWood** [vbonhomme/Momocs#68]
Hello Vincent,
Two problems show up today (latest version of Momocs):
1) plot( pca,labels=T) labels all points with the label of the first data point.
2) plot2 (pca) with default options throws the following error:
    Error in as_df.PCA(x) : could not find function "bind_cols"
Best wishes,
John

**Comment by vbonhomme** [comment]
Hi John,
1) is now corrected. Thanks for that.
2) is really strange. Maybe you should try to reinstall/library dplyr ?
All the best,
Vincent

**Comment by JohnJWood** [comment]
Hello Vincent,
Thank you for the corrections.
2) was indeed solved by reinstalling dplyr
Best wishes,
John
