### ISSUE TITLE
object 'Qm2' not found during fgProcrustes

### ISSUE THREAD

**Issue by TJ-Stammer** [vbonhomme/Momocs#84]
I'm not going to pretend that I know half the things going on in the background, but this is a recurring issue that I have run into when trying to define my own landmarks. I tried running a debug at one point and saw where Qm2 was described in two areas, the first of which was within a large block of code:

{
A <- x
A <- ldk_check(A)
p <- dim(A)[1]
k <- dim(A)[2]
n <- dim(A)[3]
temp2 <- temp1 <- array(NA, dim = c(p, k, n))
Siz <- numeric(n)
for (i in 1:n) {
    Siz[i] <- coo_centsize(A[, , i])
    temp1[, , i] <- coo_center(coo_scale(A[, , i]))
}
iter <- 0
sf <- NA
M <- temp1[, , 1]
for (i in 1:n) {
    temp1[, , i] <- fProcrustes(temp1[, , i], M)$coo1
}
M <- mshape(temp1)
Qm1 <- dist(t(matrix(temp1, k * p, n)))
Qd <- Qi <- Q <- sum(Qm1)
iter <- 0
sc <- rep(1, n)
	while (abs(Q) > tol) {
		for (i in 1:n) {
			Z1 <- temp1[, , i]
			sv <- svd(t(M) %*% Z1)
			U <- sv$v
			V <- sv$u
			Delt <- sv$d
			sig <- sign(det(t(Z1) %*% M))
			Delt[k] <- sig * abs(Delt[k])
			V[, k] <- sig * V[, k]
			phi <- U %*% t(V)
			beta <- sum(Delt)
			temp1[, , i] <- X <- sc[i] * Z1 %*% phi
		}
		M <- mshape(temp1)
		for (i in 1:n) {
			sf[i] <- sqrt(sum(diag(temp1[, , i] %*% t(M)))/(sum(diag(M %*% 
			t(M))) * sum(diag(temp1[, , i] %*% t(temp1[, 
			, i])))))
			temp2[, , i] <- sf[i] * temp1[, , i]
		}
		M <- mshape(temp2)
		sc <- sf * sc
		Qm2 <- dist(t(matrix(temp2, k * p, n)))
		Qd[iter] <- Q <- sum(Qm1) - sum(Qm2)
		Qm1 <- Qm2
		Qi[iter] <- sum(Qm2)
		iter <- iter + 1
		if (verbose) {
			cat("iteration: ", iter, "\tgain:", signif(abs(Q), 
			5), "\n")
		}
			temp1 <- temp2
	}
list(rotated = temp2, iterationnumber = iter, Q = Q, Qi = Qi, 
Qd = Qd, intereuclidean.dist = Qm2, mshape = coo_centsize(mshape(temp2)), 
cent.size = Siz)
}

The second time this code was repeated one browser step was required to get through each of the lines up until the while loop and one additional step took me to the 

list(rotated = temp2, iterationnumber = iter, Q = Q, Qi = Qi, 
Qd = Qd, intereuclidean.dist = Qm2, mshape = coo_centsize(mshape(temp2)), 
cent.size = Siz)

which is where I believe the error occurred. When this line did not throw an error in the first half of the code it was bracketed in with the while loop and a few other loops. However, where the error occurred it almost seemed like the while loop was being treated like a separate function which, when ended caused any information about Qm2 to be lost, exists('Qm2')  proof as such. Again, as a student in college still learning the ropes it could just be me throwing a wrench in the gears, but I cannot see anything in my input that would effect Qm2's declaration. Many thanks in advance.

**Comment by vbonhomme** [comment]
hi there,

thanks for pointing out this. all ldk-related methods are poorly tested so
far, so your remark is precious. do you have a reproducible example, so
that I can try to fix it ?

cheers

2015-06-18 18:30 GMT+02:00 TJ-Stammer <notifications@github.com>:

> I'm not going to pretend that I know half the things going on in the
> background, but this is a recurring issue that I have run into when trying
> to define my own landmarks. I tried running a debug at one point and saw
> where Qm2 was described in two areas, the first of which was within a large
> block of code:
>
> {
> A <- x
> A <- ldk_check(A)
> p <- dim(A)[1]
> k <- dim(A)[2]
> n <- dim(A)[3]
> temp2 <- temp1 <- array(NA, dim = c(p, k, n))
> Siz <- numeric(n)
> for (i in 1:n) {
> Siz[i] <- coo_centsize(A[, , i])
> temp1[, , i] <- coo_center(coo_scale(A[, , i]))
> }
> iter <- 0
> sf <- NA
> M <- temp1[, , 1]
> for (i in 1:n) {
> temp1[, , i] <- fProcrustes(temp1[, , i], M)$coo1
> }
> M <- mshape(temp1)
> Qm1 <- dist(t(matrix(temp1, k * p, n)))
> Qd <- Qi <- Q <- sum(Qm1)
> iter <- 0
> sc <- rep(1, n)
> while (abs(Q) > tol) {
> for (i in 1:n) {
> Z1 <- temp1[, , i]
> sv <- svd(t(M) %
>
>
>
> *% Z1) U <- sv$v V <- sv$u Delt <- sv$d sig <- sign(det(t(Z1) %*% M))
> Delt[k] <- sig * abs(Delt[k])
> V[, k] <- sig * V[, k]
> phi <- U %
>
> *% t(V) beta <- sum(Delt) temp1[, , i] <- X <- sc[i] * Z1 %*% phi
> }
> M <- mshape(temp1)
> for (i in 1:n) {
> sf[i] <- sqrt(sum(diag(temp1[, , i] %*% t(M)))/(sum(diag(M %*%
> t(M))) * sum(diag(temp1[, , i] %*% t(temp1[,
> , i])))))
> temp2[, , i] <- sf[i] * temp1[, , i]
> }
> M <- mshape(temp2)
> sc <- sf * sc
> Qm2 <- dist(t(matrix(temp2, k * p, n)))
> Qd[iter] <- Q <- sum(Qm1) - sum(Qm2)
> Qm1 <- Qm2
> Qi[iter] <- sum(Qm2)
> iter <- iter + 1
> if (verbose) {
> cat("iteration: ", iter, "\tgain:", signif(abs(Q),
> 5), "\n")
> }
> temp1 <- temp2
> }
> list(rotated = temp2, iterationnumber = iter, Q = Q, Qi = Qi,
> Qd = Qd, intereuclidean.dist = Qm2, mshape = coo_centsize(mshape(temp2)),
> cent.size = Siz)
> }
>
> The second time this code was repeated one browser step was required to
> get through each of the lines up until the while loop and one additional
> step took me to the
>
> list(rotated = temp2, iterationnumber = iter, Q = Q, Qi = Qi,
> Qd = Qd, intereuclidean.dist = Qm2, mshape = coo_centsize(mshape(temp2)),
> cent.size = Siz)
>
> which is where I believe the error occurred. When this line did not throw
> an error in the first half of the code it was bracketed in with the while
> loop and a few other loops. However, where the error occurred it almost
> seemed like the while loop was being treated like a separate function
> which, when ended caused any information about Qm2 to be lost,
> exists('Qm2') proof as such. Again, as a student in college still learning
> the ropes it could just be me throwing a wrench in the gears, but I cannot
> see anything in my input that would effect Qm2's declaration. Many thanks
> in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/84>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by TJ-Stammer** [comment]
chc2Out('MicroscopeShapeAnalysis2.chc', skip=5)->seeds
seedsldk<-def_ldk(seeds,2)
debug(fgProcrustes)
seeds<-fgProcrustes(seedsldk)

I can give you the sample chc file that I used if that would be helpful.

> traceback()
3: fgProcrustes.default(ref, tol = tol, verbose = verbose)
2: fgProcrustes.Out(seedsldk)
1: fgProcrustes(seedsldk)

In the browser the actual error occurs at the fourth level. I went about getting to it by entering n*7, s and then n until the error occurs.

In addition I noticed that depending on where the landmarks are a

Error in coo[[i]][ldk[[1]], ] : subscript out of bounds

can occur. This is tricky to reproduce because it depends on where you place the landmarks. I have no understanding of why this error occurs and it seems to be more user oriented than a problem with the code, but nonetheless the easiest way to reproduce this error is to place a landmark directly on top of the shape and then one to the left or right. I was placing one to the north and south and ran into this error infrequently, but it can still be a headache when you have to place 100+ landmarks.

I was placing my landmarks on the top and bottom of the endocarp shape near the center or North South.  

Would you like me to send you an email with the .chc?

**Comment by vbonhomme** [comment]
amazing.

"Would you like me to send you an email with the .chc?". Yeah, that would
be great. I gonna try to have a look soon but overbooked these days.

bonhomme.vincent@gmail.com

2015-06-18 20:38 GMT+02:00 TJ-Stammer <notifications@github.com>:

> chc2Out('MicroscopeShapeAnalysis2.chc', skip=5)->seeds
> seedsldk<-def_ldk(seeds,2)
> debug(fgProcrustes)
> seeds<-fgProcrustes(seedsldk)
>
> I can give you the sample chc file that I used if that would be helpful.
>
> traceback()
> 3: fgProcrustes.default(ref, tol = tol, verbose = verbose)
> 2: fgProcrustes.Out(seedsldk)
> 1: fgProcrustes(seedsldk)
>
> In the browser the actual error occurs at the fourth level. I went about
> getting to it by entering n*7, s and then n until the error occurs.
>
> In addition I noticed that depending on where the landmarks are a
>
> Error in coo[[i]][ldk[[1]], ] : subscript out of bounds
>
> can occur. This is tricky to reproduce because it depends on where you
> place the landmarks. I have no understanding of why this error occurs and
> it seems to be more user oriented than a problem with the code, but
> nonetheless the easiest way to reproduce this error is to place a landmark
> directly on top of the shape and then one to the left or right. I was
> placing one to the north and south and ran into this error infrequently,
> but it can still be a headache when you have to place 100+ landmarks.
>
> I was placing my landmarks on the top and bottom of the endocarp shape
> near the center or North South.
>
> Would you like me to send you an email with the .chc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/84#issuecomment-113252992>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by TJ-Stammer** [comment]
Sent you the chc. Best of luck!

TJ
