### ISSUE TITLE
Alignment based on first harmonic

### ISSUE THREAD

**Issue by TJ-Stammer** [vbonhomme/Momocs#89]
Hello Vince,

I've tried to align based on landmarks and also have used various coo_functions to try to align my outlines to one another. Unfortunately, I keep getting large amounts of variation due to asymmetry even when I correct for it by cutting my shapes in half and using a reflection of one side to eliminate asymmetry. Whenever I change my alignment methods I get different morphospaces. What's bugging me is that my results from Shape and Momocs usually come out drastically different and I think it's due to the fact that I normalize based on the first harmonic in Shape. I was just wondering if there was a similar option in momocs or if, due to the nature of working with coo objects, it is impossible to replicate my results. 

Thanks in advance!
TJ

**Comment by vbonhomme** [comment]
when you're happy with a pipe of coo_functions, then you can pass the Out
to efourier with norm=FALSE. See also the Details sections. eg.

data(bot)
library(magrittr)
bot %>% coo_align() %>% coo_slidedirection("E") %>% efourier(norm=FALSE)
%>% PCA() %>% plot("type")


2015-07-13 19:17 GMT+02:00 TJ-Stammer <notifications@github.com>:

> Hello Vince,
>
> I've tried to align based on landmarks and also have used various
> coo_functions to try to align my outlines to one another. Unfortunately, I
> keep getting large amounts of variation due to asymmetry even when I
> correct for it by cutting my shapes in half and using a reflection of one
> side to eliminate asymmetry. Whenever I change my alignment methods I get
> different morphospaces. What's bugging me is that my results from Shape and
> Momocs usually come out drastically different and I think it's due to the
> fact that I normalize based on the first harmonic in Shape. I was just
> wondering if there was a similar option in momocs or if, due to the nature
> of working with coo objects, it is impossible to replicate my results.
>
> Thanks in advance!
> TJ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/Momocs/issues/89>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by TJ-Stammer** [comment]
Thanks!
